apiVersion: v1

# We are creating a Secret resource.
kind: Secret

# Metadata stores information about the Secret.
metadata:
  # Unique name of the Secret.
  name: mongo-secret

# Type of Secret.
# "Opaque" is the default type for storing custom key-value pairs.
type: Opaque

# Secret data stored as Base64-encoded values.
# Note: Base64 is NOT encryption. Anyone can decode it easily.
data:
  # Username
  mongo-user: bW9uZ291c2Vy
  
  # Password
  mongo-password: bW9uZ29wYXNzd29yZA==
