apiVersion: v1

# We are creating a ConfigMap resource.
kind: ConfigMap

# Metadata stores information about the ConfigMap.
metadata:
  # Unique name of the ConfigMap.
  name: game-demo

  # Optional: Namespace where this ConfigMap will be created.
  # namespace: default

  # Optional: Labels used to identify or group this ConfigMap.
  labels:
    app: mongodb

  # Optional: Extra information about this ConfigMap.
  annotations:
    created-by: kaif

# Stores configuration as plain text key-value pairs.
# Use ConfigMaps for non-sensitive data.
# (Passwords, API keys, and tokens should go in a Secret instead.)
data:
  # MongoDB service name inside the Kubernetes cluster.
  # "my-service" is the name of defined service 
  # so make sure if you keep name in service.yml make sure it matches here
  mongo-url: my-service

  # Other common examples:
  # database-name: mydb
  # app-mode: production
  # log-level: info
