apiVersion: v1

# We are creating a Secret resource.
kind: Secret

# Metadata stores information about the Secret.
metadata:
  # Unique name of the Secret.
  name: mongo-secret

  # Optional: Namespace where this Secret will be created.
  namespace: default

  # Optional: Labels used to identify or group this Secret.
  labels:
    app: mongodb

  # Optional: Extra information about this Secret.
  annotations:
    created-by: kaif

# Type of Secret.
# "Opaque" is used for custom key-value secrets.
type: Opaque

# Secret values encoded in Base64.
# Use this when you already have Base64 values.
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==

# Secret values in plain text.
# Kubernetes automatically converts them to Base64.
# Usually easier to write than "data".
# stringData:
#   mongo-user: mongouser
#   mongo-password: mongopassword

# Optional: Prevent this Secret from being updated.
immutable: true
