name: compose-environment

services:
  # Backend API
  backend:
    image: node:22-alpine

    # Define environment variables explicitly.
    
    # Compose automatically reads the `.env` file from the project directory and replaces
    # `${VARIABLE}` with its value.
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

    command:
      - env


  # Mongo Express
  mongo-express:
    image: mongo-express:latest

    # Inject environment variables directly
    # into the container from a file.
    
    # Unlike `.env`, Compose does NOT use this
    # file for variable interpolation.
    env_file:
      - ./app.env

    command:
      - env

  # Worker
  worker:
    image: alpine

    # `environment` and `env_file` can be combined.
    
    # If the same variable exists in both,
    # `environment` takes precedence.
    env_file:
      - ./app.env

    environment:
      APP_MODE: production

    command:
      - env

  # Production API
  production-api:
    image: backend-api:latest

    # Mount Docker-managed secrets into the container.
    
    # Unlike environment variables, secrets are stored
    # as files inside the container instead of being
    # exposed through the process environment.
    
    # Useful for passwords, API keys and certificates.
    secrets:
      - db_password

# Declare Docker-managed secrets.
# Each secret is loaded from a file on the host
# and mounted into the container at runtime.
secrets:
  db_password:
    file: ./secrets/db_password.txt
