
FROM python:latest

WORKDIR /app

COPY . .

RUN pip install -r requirements-dev.txt

ENV APP_ENV=production

EXPOSE 80

USER nobody

HEALTHCHECK --interval=30s \
  CMD curl -f http://localhost:8000/health || exit 1

CMD ["uvicorn", "main:app", "--port", "8000"]